# Generated by Django 2.2.18 on 2021-02-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_table', '0002_auto_20210220_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variables',
            name='value',
            field=models.TextField(),
        ),
    ]
