# Generated by Django 2.2.18 on 2021-02-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_table', '0003_auto_20210220_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='type',
            field=models.CharField(default='session', max_length=100),
            preserve_default=False,
        ),
    ]
