# Generated by Django 2.2.18 on 2021-02-20 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_table', '0005_remove_variables_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 0, 32, 9, 384093)),
        ),
        migrations.AddField(
            model_name='variables',
            name='previous',
            field=models.TextField(default=models.TextField()),
        ),
        migrations.AddField(
            model_name='variables',
            name='recently_modified',
            field=models.BooleanField(default=False),
        ),
    ]
